### ISSUE TITLE
refine local install for beta testers (non-HPC integration)

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/htr2hpc#10]
## testing instructions
- [x] confirm escriptorium successfully sends email
- [x] confirm can login with princeton netid
- [x] confirm larger files can be uploaded that previously failed
- [x] confirm that you see the dev-14.2 version number in the footer on the homepage

## implementation notes
- [x] email configuration
- [x] integrate pucas / Princeton netid 
- [x] update configuration for upload file size limitations
- [x] deploy a known version and include version info on the homepage

**Comment by cmroughan** [comment]
# Email testing

I tested three functions that send emails in eScriptorium: initiating an export from a document, inviting another user to a team, and inviting a new email address to the instance (using one of my other emails). 

## Exporting from a document

Email successfully sent, with a bug.

> from: [dev email]
> subject: Your escriptorium export is ready.
> You can find it here users/3/export_doc2_test_shared_document_alto_202410090150.zip

The link in the email went to http://example.com/media/users/3/export_doc2_test_shared_document_alto_202410090150.zip instead of the test instance. So the instance URL needs to be fixed somewhere.

## Inviting a user to a team

Email successfully sent; link worked 👍 

> from: [dev email]
> subject: Christine Roughan invites you to eScriptorium!
> Hello [my email],
> Christine Roughan is inviting you to join his/her team test team on eScriptorium!
All you need to do is click on the link below:
[URL]/accept/group/2c6507cc15f24f83b1f164ad8bcd5f56/
> Sincerely, the eScriptorium team.

## Inviting a new email to the instance

Email successfully sent; link worked. We will want to discuss how invites would be handled in a real use case.

> from: [dev email]
> subject: Christine Roughan invites you to eScriptorium!
> Hello [me],
> Christine Roughan is inviting you to join eScriptorium! All you need to do is click on the link below:
[URL]/accept/7c61b20fe1dc4310b2ae8bb63a1d863c/
> Sincerely, the eScriptorium team.

Only admins have user invite permissions, but this invite link *does* circumnavigate the CAS login. Presumably we will want to write it so that CAS is required in the end.

**Comment by cmroughan** [comment]
# Login testing

Logging in with the netID worked 👍 Clicking the CAS link led to an error the first time, likely because the netID email in question was already in use for my test account. But it apparently still created the account, because clicking the link a second time went through without issue. I have since been able to log back in with CAS without encountering any problems.

# Larger file uploads

In recent tests, files of up to 159.7 MB have successfully uploaded. Testing this evening was getting stuck on the "Import queued" message, however, so I will take another look at things tomorrow.

# Version number

This is indeed visible and so can be automatically grabbed for future runs of automated testing 👍

**Comment by rlskoeser** [comment]
@cmroughan for the email that had the wrong url - do you want to update the test site domain here https://test-htr.lib.princeton.edu/admin/sites/site/ and test it again?  (I'm a bit curious why the others work and this one doesn't).

@cmroughan would you also check things off in the issue description based on your testing?

**Comment by cmroughan** [comment]
Good find, that domain change fixed it! Emails now work with successful links included.
