### ISSUE TITLE
clean up temporary data after segmentation training completes

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/htr2hpc#30]

**Comment by cmroughan** [comment]
Summarizing some considerations to keep in mind:

- The clean up steps should remove all of the temporary data from the cluster as a final step in the process -- fortunately, this temporary data is contained inside an identified working directory.
- Clean up steps should also be run on error handling, so that partial temporary data does not cause clutter if the script fails for some reason.
- The script should have a flag that prevents the clean up steps from running, which we will want during testing and debugging.
- Consider transferring the slurm `segtrain-####.out` files to the VMs rather than deleting, so that these can serve debugging purposes as needed.

Note that in the API, Task Report Instances have a `messages` attribute (not read_only) -- consider sending the text of `segtrain-####.out` there. If you have a task report instance with a value for `messages`, you can see what that looks like by going to `https://test-htr.lib.princeton.edu/quotas/[TASK_PK]` (inputting the relevant TASK_PK).

**Comment by cmroughan** [comment]
On the possibility of passing the `segtrain-####.out` data to an eScriptorium Task Report instance via the API: this data can successfully be passed in via the `messages` attribute. However, the display in the eScriptorium GUI does not suit the monospaced command line output, so the text is not made available very cleanly. It still would work as an aid for troubleshooting, but I might see whether the key data could be extracted out instead...

<img width="1355" alt="Screenshot 2024-11-27 at 2 36 34 PM" src="https://github.com/user-attachments/assets/4d5fba69-5d78-4ce3-b381-bcc454089d04">
<img width="1342" alt="Screenshot 2024-11-27 at 2 36 57 PM" src="https://github.com/user-attachments/assets/8c9cf09a-2653-4e52-b53f-e0469dce09e2">

**Comment by rlskoeser** [comment]
implemented in #32
